from __future__ import annotations

DEFAULT_GENERATE_MODEL = "sdxl.base"
DEFAULT_GENERATE_PROMPT = "a dramatic product photo, studio lighting, clean background"
DEFAULT_GENERATE_NEGATIVE_PROMPT = "blurry, low quality"
DEFAULT_GENERATE_WIDTH = 1024
DEFAULT_GENERATE_HEIGHT = 1024
DEFAULT_GENERATE_STEPS = 30
DEFAULT_GENERATE_GUIDANCE_SCALE = 6.5
DEFAULT_GENERATE_SEED = 1234
DEFAULT_GENERATE_DEVICE = "mps"
DEFAULT_GENERATE_DTYPE = "fp16"
DEFAULT_GENERATE_OUTPUT_PATH = "/Users/robinsongarcia/Desktop/out.png"

DEFAULT_GENERATE_REQUEST_PAYLOAD = {
    "device": DEFAULT_GENERATE_DEVICE,
    "dtype": DEFAULT_GENERATE_DTYPE,
    "guidance_scale": DEFAULT_GENERATE_GUIDANCE_SCALE,
    "height": DEFAULT_GENERATE_HEIGHT,
    "model": DEFAULT_GENERATE_MODEL,
    "negative_prompt": DEFAULT_GENERATE_NEGATIVE_PROMPT,
    "output_path": DEFAULT_GENERATE_OUTPUT_PATH,
    "prompt": DEFAULT_GENERATE_PROMPT,
    "seed": DEFAULT_GENERATE_SEED,
    "steps": DEFAULT_GENERATE_STEPS,
    "width": DEFAULT_GENERATE_WIDTH,
}
